// API configuration - uses config.js generated by backend
// Falls back to localhost:8000 if config.js is not loaded
const API_BASE_URL = (typeof API_CONFIG !== 'undefined') ? API_CONFIG.baseUrl : 'http://localhost:8000';


// API call for text generation
async function callGenerateAPI(prompt, temperature, maxTokens, documentContext = null) {
    const response = await fetch(`${API_BASE_URL}/generate`, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
        },
        body: JSON.stringify({
            prompt: prompt,
            temperature: temperature,
            max_tokens: maxTokens,
            document_context: documentContext
        })
    });

    if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
    }

    return await response.json();
}

// API call for attention analysis
async function callAnalyzeAPI(text, attnLayer) {
    const response = await fetch(`${API_BASE_URL}/analyze`, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
        },
        body: JSON.stringify({
            answer: text,
            attn_layer: attnLayer
        })
    });

    if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
    }

    return await response.json();
}

// API call for comparison model analysis
async function callCompareAPI(text, attnLayer) {
    const response = await fetch(`${API_BASE_URL}/compare`, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
        },
        body: JSON.stringify({
            answer: text,
            attn_layer: attnLayer
        })
    });

    if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
    }

    return await response.json();
}

// Get model names
async function getModels() {
    const response = await fetch(`${API_BASE_URL}/models`);

    if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
    }

    return await response.json();
}
